#Persisted Channels storage file  by EFI Analytics, Inc
#Last Saved on: Mon Dec 25 09:01:35 EST 2023
#Mon Dec 25 09:01:35 EST 2023
_(\ (\ deltatime\ <\ 1000.0\ )\ )\ ?\ ((\ (\ tsFuelFlowGph\ *\ deltatime\ /\ 3600.0\ )\ ))\ \:\ (0.0)=5.437679108480149E-4
_(\ (\ tsInputSpeedMPH\ *\ 1.60934\ )\ /\ 3600.0\ *\ deltatime\ )=0.0
_(\ tsInputSpeedMPH\ /\ 3600.0\ *\ deltatime\ )=0.0
