#Vehicles Attributes.
#TunerStudio by Philip Tobin
#Fri Dec 08 17:48:04 EST 2023
converterStall=
injectorSize=700
firstGearRatio=
fourthGearRatio=
finalDriveRatio=
transmissionType=Manual
fifthGearRatio=
weight=
thirdGearRatio=
sixthGearRatio=
secondGearRatio=
engineDisplacement=1839
