#Persisted Channels storage file  by EFI Analytics, Inc
#Last Saved on: Wed Feb 21 12:06:14 EST 2024
#Wed Feb 21 12:06:14 EST 2024
_(\ (\ tsInputSpeedMPH\ *\ 1.60934\ )\ /\ 3600.0\ *\ deltatime\ )=15.365949343405289
_(\ (\ deltatime\ <\ 1000.0\ )\ )\ ?\ ((\ (\ tsFuelFlowGph\ *\ deltatime\ /\ 3600.0\ )\ ))\ \:\ (0.0)=0.0
_(\ tsInputSpeedMPH\ /\ 3600.0\ *\ deltatime\ )=257.13452543147235
