#Vehicles Attributes.
#TunerStudio by Philip Tobin
#Tue Dec 19 09:15:14 EST 2023
converterStall=
firstGearRatio=
fourthGearRatio=
finalDriveRatio=
transmissionType=Manual
fifthGearRatio=
weight=
thirdGearRatio=
sixthGearRatio=
secondGearRatio=
