#Vehicles Attributes.
#TunerStudio by Philip Tobin
#Sun Feb 25 14:14:20 EST 2024
injectorSize=260
converterStall=
firstGearRatio=
fourthGearRatio=
finalDriveRatio=
transmissionType=Manual
fifthGearRatio=
weight=
thirdGearRatio=
sixthGearRatio=
secondGearRatio=
engineDisplacement=1898
