#Project Attributes.
#TunerStudio by EFI Analytics, Inc
#Last Saved on: Fri Nov 03 20:20:47 EDT 2023
#Fri Nov 03 20:20:47 EDT 2023
logTuningPanel_selectionTable2=sparkTbl
CommSettingMSCommDriver.RS232\ Serial\ InterfaceBaud\ Rate=115200
logTuningPanel_selectionTable1=veTable1Tbl
airConAir\ Conditioning_width=408
idleSettingsIdle\ Settings_Y=155
iacClosedLoop_curve_showText=true
idleSettingsIdle\ Settings_X=1357
CommSettingDESKTOP-BO0JBU1CommDriver.controllerInterfaceId=RS232 Serial Interface
canId=0
firmwareDescription=Speeduino 2023.05
iacPwmCrank_curveIAC\ PWM\ Cranking\ Duty_height=280
io_summaryI/O\ Summary_width=388
WueAnalyzeConsole.warmup_analyzer_curve_selectedDash=Standard
afrTable1TblAFR\ Table_width=559
iacPwmCrank_curve_showText=true
prgm_out_configProgrammable\ outputs_width=484
CommSettingDESKTOP-BO0JBU1CommDriver.RS232\ Serial\ InterfaceBluetooth\ Port=false
CommSettingDESKTOP-BO0JBU1CommDriver.RS232\ Serial\ InterfaceCom\ Port=COM5
reset_controlReset\ Control_height=216
idleUpSettingsIdle\ Up\ Settings_height=380
CommSettingBaud\ Rate=115200
iacPwmCrank_curveIAC\ PWM\ Cranking\ Duty_Y=376
iacPwmCrank_curveIAC\ PWM\ Cranking\ Duty_X=766
airConAir\ Conditioning_height=718
veTableDialogVE\ Table_width=578
veTableDialogVE\ Table_height=581
projectDescription=
VeAnalyzeConsole.veTable1Tbl_selectedDash=Standard
useCommonDashboardDir=false
engine_constantsEngine\ Constants_width=594
useCommonTuneViewDir=false
egoControlAFR/O2_height=497
iacPwmCrank_curveIAC\ PWM\ Cranking\ Duty_width=388
CommSettingDESKTOP-BO0JBU1CommDriver.RS232\ Serial\ InterfaceBaud\ Rate=115200
fanSettingsFan\ Settings_width=417
idleUpSettingsIdle\ Up\ Settings_width=388
projectName=1999-Miata
CommSettingMSCommDriver.RS232\ Serial\ InterfaceBluetooth\ Port=false
iacClosedLoop_curve_Set\ X\ Axis\ Minimum=-40.0
CommSettingDESKTOP-1B7VEFECommDriver.RS232\ Serial\ InterfaceBluetooth\ Port=false
engine_constantsEngine\ Constants_Y=203
engine_constantsEngine\ Constants_X=668
commPort=COM1
fanSettingsFan\ Settings_Y=328
fanSettingsFan\ Settings_X=751
Triggers.ActiveTriggers=TriggeredPage0 Refresh\:  vssRefresh > 0 |
tsSupplementalFieldsVehicle\ Specifications_height=444
userDash0.FileName=Default.dash
idleUpSettingsIdle\ Up\ Settings_Y=254
engine_constantsEngine\ Constants_height=625
idleUpSettingsIdle\ Up\ Settings_X=541
egoControlAFR/O2_Y=267
batCalCalibrate\ voltage\ reading_width=388
serial3IOSecondary\ Serial\ IO\ interface_height=306
egoControlAFR/O2_X=766
userDash0.DashName=Default
prgm_out_configProgrammable\ outputs_Y=291
prgm_out_configProgrammable\ outputs_X=718
iacClosedLoop_curveIdle\ RPM\ Targets_height=505
airConAir\ Conditioning_Y=157
airConAir\ Conditioning_X=756
CommSettingMSCommDriver.controllerInterfaceId=RS232 Serial Interface
lambdaTable1TblLambda\ Table_width=695
egoControlAFR/O2_width=388
baudRate=115200
idleSettingsIdle\ Settings_height=751
lambdaTable1TblLambda\ Table_Y=292
refTable_002_txtY2=18
lambdaTable1TblLambda\ Table_X=612
refTable_002_txtY1=8.5
CommSettingCom\ Port=COM1
batCalCalibrate\ voltage\ reading_Y=426
batCalCalibrate\ voltage\ reading_X=766
fanSettingsFan\ Settings_height=376
idleAdvanceSettingsIdle\ Advance\ Settings_Y=403
idleAdvanceSettingsIdle\ Advance\ Settings_X=236
batCalCalibrate\ voltage\ reading_height=180
logFileDir=C\:\\Users\\Solidworks\\OneDrive\\TunerStudio Files\\Alejo_NIN-TunerStudio-Projects\\1999-Miata\\DataLogs
serial3IOSecondary\ Serial\ IO\ interface_width=764
idle_advance_curve_showText=true
iacClosedLoop_curveIdle\ RPM\ Targets_Y=363
lambdaTable1TblLambda\ Table_height=447
iacClosedLoop_curveIdle\ RPM\ Targets_X=727
ecuConfigFile=mainController.ini
veTableDialogVE\ Table_Y=225
veTableDialogVE\ Table_X=671
tsSupplementalFieldsVehicle\ Specifications_Y=294
tsSupplementalFieldsVehicle\ Specifications_X=587
CommSettingDESKTOP-1B7VEFECommDriver.RS232\ Serial\ InterfaceCom\ Port=COM15
refTable_002_txtX2=4.5
refTable_002_txtX1=0.5
tsSupplementalFieldsVehicle\ Specifications_width=745
prgm_out_configProgrammable\ outputs_height=449
iacClosedLoop_curveIdle\ RPM\ Targets_width=665
CommSettingMSCommDriver.RS232\ Serial\ InterfaceCom\ Port=COM15
serial3IOSecondary\ Serial\ IO\ interface_Y=363
warmup_afr_curve_Set\ X\ Axis\ Minimum=-40.0
serial3IOSecondary\ Serial\ IO\ interface_X=578
CommSettingDESKTOP-1B7VEFECommDriver.RS232\ Serial\ InterfaceBaud\ Rate=115200
dashBoardFile=\\dashboard\\\\dashboard.dash
afrTable1TblAFR\ Table_height=447
tuneFileDir=C\:\\Users\\garage\\OneDrive\\TunerStudio Files\\Alejo_NIN-TunerStudio-Projects\\1999-Miata
CommSettingDESKTOP-1B7VEFECommDriver.controllerInterfaceId=RS232 Serial Interface
idleAdvanceSettingsIdle\ Advance\ Settings_height=400
reset_controlReset\ Control_width=388
reset_controlReset\ Control_Y=408
io_summaryI/O\ Summary_Y=194
reset_controlReset\ Control_X=766
io_summaryI/O\ Summary_X=235
iacPwmCrank_curve_Set\ X\ Axis\ Minimum=-40.0
warmup_analyzer_curve_Set\ X\ Axis\ Minimum=-40.0
afrTable1TblAFR\ Table_Y=292
afrTable1TblAFR\ Table_X=680
userDash1.FileName=Acceleration_Performance.dash
selectedComDriver=Multi Interface MegaSquirt Driver
io_summaryI/O\ Summary_height=718
idleSettingsIdle\ Settings_width=388
idleAdvanceSettingsIdle\ Advance\ Settings_width=1304
userDash1.DashName=Acceleration Performance
ecuSettings=AFR|CAN_COMMANDS_OFF|FAHRENHEIT|NEW_COMMS|enablehardware_test_OFF|resetcontrol_standard|
