#Vehicles Attributes.
#TunerStudio by Philip Tobin
#Mon Jan 29 08:31:00 EST 2024
converterStall=
firstGearRatio=
fourthGearRatio=
finalDriveRatio=
transmissionType=Manual
fifthGearRatio=
weight=
thirdGearRatio=
sixthGearRatio=
secondGearRatio=
